### ISSUE TITLE
ci: Publish AMI images from master

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#334]
**Is your feature request related to a problem? Please describe.**
Consuming vanilla images for #208 

**Describe the solution you'd like**
the CI should publish the images generated to amazon AWS and make them public once tests are passing and the repository has been published.

Images have to be reusable by packer templates, so there is no need to manually update the raw disk anymore for downstream derivatives.

**Describe alternatives you've considered**
N/A

**Additional context**
#302 #217

**Comment by Itxaka** [comment]
some preliminary work on this draft: https://github.com/rancher-sandbox/cOS-toolkit/pull/350

Basically:
 - Runs after publish
 - Only on master
 - For each flavor defined (opensuse, fedora, ubuntu)
 - Uses the latest cos*recovery image as base AMI (this have to be pushed manually from time to time unless we made that part of our workflow?
 - uses packer-aws target and 3 env vars to build the proper flavor
   - PKR_VAR_cos_version -> Sets the version to build the image from
   - PKR_VAR_flavor -> sets the flavor to name the image
   - PKR_VAR_aws_cos_install_args -> Sets the command used to deploy the image, using the --docker-image to pass the repo that we just published

I noticed thanks to this that both the fedora and ubuntu image do not pass the mtree verification, which probbly means that they have some extra files somehow? Have to check that.

**Comment by Itxaka** [comment]
FYI I opened https://github.com/hashicorp/packer-plugin-amazon/issues/103 upstream in case there is interest into allowing the post-processor from packer `amazon-import` to also import and register snapshots as AMIs. That would make this process much simpler for us as we could upload the recovery images automatically to amazon for others to consume.

**Comment by mudler** [comment]
Something seems still not working https://github.com/rancher-sandbox/cOS-toolkit/runs/2975749457?check_suite_focus=true

**Comment by Itxaka** [comment]
Good, because I didnt expect it to work out of the box lmao

**Comment by Itxaka** [comment]
after 5 or 6 fixes, images are now pushed from master to aws, set as public so anyone can consume them
